// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"example.com/mud/world/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAction creates a new instance of MockAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAction {
	mock := &MockAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAction is an autogenerated mock type for the Action type
type MockAction struct {
	mock.Mock
}

type MockAction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAction) EXPECT() *MockAction_Expecter {
	return &MockAction_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockAction
func (_mock *MockAction) Execute(ev *entities.Event) error {
	ret := _mock.Called(ev)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entities.Event) error); ok {
		r0 = returnFunc(ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAction_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAction_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ev *entities.Event
func (_e *MockAction_Expecter) Execute(ev interface{}) *MockAction_Execute_Call {
	return &MockAction_Execute_Call{Call: _e.mock.On("Execute", ev)}
}

func (_c *MockAction_Execute_Call) Run(run func(ev *entities.Event)) *MockAction_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.Event
		if args[0] != nil {
			arg0 = args[0].(*entities.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAction_Execute_Call) Return(err error) *MockAction_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAction_Execute_Call) RunAndReturn(run func(ev *entities.Event) error) *MockAction_Execute_Call {
	_c.Call.Return(run)
	return _c
}
