// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"example.com/mud/world/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCondition creates a new instance of MockCondition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCondition(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCondition {
	mock := &MockCondition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCondition is an autogenerated mock type for the Condition type
type MockCondition struct {
	mock.Mock
}

type MockCondition_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCondition) EXPECT() *MockCondition_Expecter {
	return &MockCondition_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockCondition
func (_mock *MockCondition) Check(ev *entities.Event) (bool, error) {
	ret := _mock.Called(ev)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entities.Event) (bool, error)); ok {
		return returnFunc(ev)
	}
	if returnFunc, ok := ret.Get(0).(func(*entities.Event) bool); ok {
		r0 = returnFunc(ev)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*entities.Event) error); ok {
		r1 = returnFunc(ev)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCondition_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockCondition_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ev *entities.Event
func (_e *MockCondition_Expecter) Check(ev interface{}) *MockCondition_Check_Call {
	return &MockCondition_Check_Call{Call: _e.mock.On("Check", ev)}
}

func (_c *MockCondition_Check_Call) Run(run func(ev *entities.Event)) *MockCondition_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.Event
		if args[0] != nil {
			arg0 = args[0].(*entities.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCondition_Check_Call) Return(b bool, err error) *MockCondition_Check_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCondition_Check_Call) RunAndReturn(run func(ev *entities.Event) (bool, error)) *MockCondition_Check_Call {
	_c.Call.Return(run)
	return _c
}
