// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"example.com/mud/world/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockPublisher
func (_mock *MockPublisher) Publish(room *entities.Entity, text string, exclude []*entities.Entity) {
	_mock.Called(room, text, exclude)
	return
}

// MockPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - room *entities.Entity
//   - text string
//   - exclude []*entities.Entity
func (_e *MockPublisher_Expecter) Publish(room interface{}, text interface{}, exclude interface{}) *MockPublisher_Publish_Call {
	return &MockPublisher_Publish_Call{Call: _e.mock.On("Publish", room, text, exclude)}
}

func (_c *MockPublisher_Publish_Call) Run(run func(room *entities.Entity, text string, exclude []*entities.Entity)) *MockPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.Entity
		if args[0] != nil {
			arg0 = args[0].(*entities.Entity)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*entities.Entity
		if args[2] != nil {
			arg2 = args[2].([]*entities.Entity)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPublisher_Publish_Call) Return() *MockPublisher_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_Publish_Call) RunAndReturn(run func(room *entities.Entity, text string, exclude []*entities.Entity)) *MockPublisher_Publish_Call {
	_c.Run(run)
	return _c
}

// PublishTo provides a mock function for the type MockPublisher
func (_mock *MockPublisher) PublishTo(room *entities.Entity, recipient *entities.Entity, text string) {
	_mock.Called(room, recipient, text)
	return
}

// MockPublisher_PublishTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTo'
type MockPublisher_PublishTo_Call struct {
	*mock.Call
}

// PublishTo is a helper method to define mock.On call
//   - room *entities.Entity
//   - recipient *entities.Entity
//   - text string
func (_e *MockPublisher_Expecter) PublishTo(room interface{}, recipient interface{}, text interface{}) *MockPublisher_PublishTo_Call {
	return &MockPublisher_PublishTo_Call{Call: _e.mock.On("PublishTo", room, recipient, text)}
}

func (_c *MockPublisher_PublishTo_Call) Run(run func(room *entities.Entity, recipient *entities.Entity, text string)) *MockPublisher_PublishTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.Entity
		if args[0] != nil {
			arg0 = args[0].(*entities.Entity)
		}
		var arg1 *entities.Entity
		if args[1] != nil {
			arg1 = args[1].(*entities.Entity)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPublisher_PublishTo_Call) Return() *MockPublisher_PublishTo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_PublishTo_Call) RunAndReturn(run func(room *entities.Entity, recipient *entities.Entity, text string)) *MockPublisher_PublishTo_Call {
	_c.Run(run)
	return _c
}
