// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"example.com/mud/world/scheduler"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduler creates a new instance of MockScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduler {
	mock := &MockScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduler is an autogenerated mock type for the Scheduler type
type MockScheduler struct {
	mock.Mock
}

type MockScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduler) EXPECT() *MockScheduler_Expecter {
	return &MockScheduler_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockScheduler
func (_mock *MockScheduler) Add(job *scheduler.Job) {
	_mock.Called(job)
	return
}

// MockScheduler_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockScheduler_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - job *scheduler.Job
func (_e *MockScheduler_Expecter) Add(job interface{}) *MockScheduler_Add_Call {
	return &MockScheduler_Add_Call{Call: _e.mock.On("Add", job)}
}

func (_c *MockScheduler_Add_Call) Run(run func(job *scheduler.Job)) *MockScheduler_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scheduler.Job
		if args[0] != nil {
			arg0 = args[0].(*scheduler.Job)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScheduler_Add_Call) Return() *MockScheduler_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockScheduler_Add_Call) RunAndReturn(run func(job *scheduler.Job)) *MockScheduler_Add_Call {
	_c.Run(run)
	return _c
}
