name: Build and Deploy

on:
  push:
    # branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      RELEASE_DIR: release-${{ github.sha }}
      REMOTE_APP_DIR: /opt/mud
      REMOTE_RELEASES: /opt/mud/releases
      REMOTE_CURRENT: /opt/mud/current
      SERVICE_NAME: mud-server.service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Build server
        run: |
          mkdir -p "${{ env.RELEASE_DIR }}"
          go build -o "${{ env.RELEASE_DIR }}/mud-server"

      - name: Upload release to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ${{ env.RELEASE_DIR }}
          target: ${{ env.REMOTE_RELEASES }}

      - name: Activate release & restart service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -euo pipefail

            RELEASE_PATH="${{ env.REMOTE_RELEASES }}/${{ env.RELEASE_DIR }}"
            CURRENT_DIR="${{ env.REMOTE_CURRENT }}"
            APP_DIR="${{ env.REMOTE_APP_DIR }}"
            SERVICE="${{ env.SERVICE_NAME }}"

            # Ensure base dirs exist
            sudo mkdir -p "${APP_DIR}" "${{ env.REMOTE_RELEASES }}" "${CURRENT_DIR}"
            # Ensure a data directory exists in current (managed outside CI/CD)
            sudo mkdir -p "${CURRENT_DIR}/data"

            sudo chown -R mud:mud "${APP_DIR}"
            sudo chown -R mud:mud "${RELEASE_PATH}"
            sudo chown -R mud:mud "${CURRENT_DIR}"

            # Make sure binary is executable
            sudo chmod +x "${RELEASE_PATH}/mud-server"

            # Inside CURRENT_DIR:
            # - 'release' symlink points to the newly uploaded release dir
            # - 'mud-server' symlink points to ./release/mud-server
            sudo -u mud ln -sfn "${RELEASE_PATH}" "${CURRENT_DIR}/release"
            sudo -u mud ln -sfn "release/mud-server" "${CURRENT_DIR}/mud-server"

            # (Optional) keep a 'previous' pointer for quick rollback:
            # if [ -L "${CURRENT_DIR}/previous" ]; then sudo -u mud rm -f "${CURRENT_DIR}/previous"; fi
            # sudo -u mud ln -sfn "${RELEASE_PATH}" "${CURRENT_DIR}/previous"

            # Restart service
            sudo systemctl daemon-reload
            sudo systemctl restart "${SERVICE}"
            sudo systemctl --no-pager -l status "${SERVICE}" || true
